name: Fix README for non-template repository

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README.md with repository name
        run: |
          FULL_REPO="${{ github.repository }}"
          ORG_NAME=$(echo "${FULL_REPO}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${FULL_REPO}" | cut -d '/' -f 2)
          echo "# ${REPO_NAME}" > README.md
          echo "- Your album is live at [${REPO_NAME}](https://rathnasorg.github.io/i4tow/a/${REPO_NAME}/${ORG_NAME}.github.io)" >> README.md
          echo "- You can customize/selfhost and be awesome, reach me at i4tow@rathnas.com" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README.md [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
